### ISSUE TITLE
Duplicated Evidence from Data Feed

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_release#85]
By checking the combination of `target_id, disease_id & json_doc_hashdig` from the validated JSON of all datasources as of `18.06`, couple of those are still having duplicated evidence.

 EVA - 106 (Despite adding rs_id to `unique_association_field`, probably due to >1 clinvar traits mapping to same EFO terms, needs following up with EVA & @gkos-bio)

GWAS - 784 (Olga has flag this to GWAS curator for checking)

ATLAS - 40459 (Suhaib planned to add probe_id to `unique_association_field` aim this will solve the issue)

EUROPEPMC - 519807 (example sent to them but no feedback yet)

PHEWAS - 117 (check with Eliseo)

**Comment by ElaineMcA** [comment]
EVA - 106 (Despite adding rs_id to unique_association_field, probably due to >1 clinvar traits mapping to same EFO terms, needs following up with EVA & @gkos-bio)

- Update 17JUL2018: Partially fixed in 18.08.  Ontology mapping required @Adam and Gautier.

GWAS - 784 (Olga has flag this to GWAS curator for checking)

- Update 17JUL2018- Under investigation.

ATLAS - 40459 (Suhaib planned to add probe_id to unique_association_field aim this will solve the issue)

- Update 17JUL2018: Fixed in 18.08.

EUROPEPMC - 519807 (example sent to them but no feedback yet)

- Update 17JUL2018: Need to follow-up.

PHEWAS - 117 (check with Eliseo)

- Update 17JUL2018: Need to follow-up.

**Comment by ckongEbi** [comment]
Look for rows for counts > 1, which will be duplicates

EVA: [1806_dup_eva_2.txt](https://github.com/opentargets/data_release/files/2201861/1806_dup_eva_2.txt)

GWAS: [1806_dup_gwas_2.txt](https://github.com/opentargets/data_release/files/2201862/1806_dup_gwas_2.txt)

PHEWAS: [18.06_phewas_2.txt](https://github.com/opentargets/data_release/files/2201882/18.06_phewas_2.txt)

EPMC & ATLAS: 
https://drive.google.com/open?id=1levWwb8FgsmGm2bPsbS8ZZGOK1OAPSFv

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #60](https://github.com/opentargets/platform/issues/60) via [**ZenHub**](https://www.zenhub.com/)
